intel-oneapi-compilers: copied from upstream develop branch
* Removed code that caused:
  Error: NameError: name 'EnvironmentModifications' is not defined